import { addAsyncActionPostfixes } from '@/utils/actionTypeCreator';

export const userDetailsTypes = {
  ...addAsyncActionPostfixes({
    USER_LOGIN: 'USER_LOGIN',
    USER_SIGNUP: 'USER_SIGNUP',
    BUSINESS_ONBOARDING: 'BUSINESS_ONBOARDING',
    CREATE_MENU_LIST: 'CREATE_MENU_LIST',
    GET_MENU_LIST_FROM_API: 'GET_MENU_LIST_FROM_API',
    GET_VISIBILITY: 'GET_VISIBILITY',
    UPDATE_VISIBILITY: 'UPDATE_VISIBILITY',
    GET_CATEGORIES: 'GET_CATEGORIES',
    UPDATE_ITEM_BY_ID: 'UPDATE_ITEM_BY_ID',
    CREATE_ORDER: 'CREATE_ORDER',
    UPDATE_ORDER_STATUS:'UPDATE_ORDER_STATUS',
    CLOSE_SUCCESS_MESSAGE: 'CLOSE_SUCCESS_MESSAGE',
    GET_ORDER_LIST: 'GET_ORDER_LIST'
  }),
  SAVE_CART: 'SAVE_CART',
  ITEMS_COUNT:'ITEMS_COUNT', 
  ADD_FAVOURITES: 'ADD_FAVOURITES',
  FILTERED_ITEMS: 'FILTERED_ITEMS',
};
